import type { Metadata } from "next";
import { Roboto } from 'next/font/google';
import "./globals.css";
import QueryClientContextProvider from "./query-client-provider";
import { ThemeProvider } from "./contexts/themeContext";
import '@fortawesome/fontawesome-svg-core/styles.css';
import { config } from '@fortawesome/fontawesome-svg-core';

config.autoAddCss = false;

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "YouTube",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                const storedTheme = localStorage.getItem('theme') || 'light';
                if (storedTheme === 'dark') {
                  document.documentElement.classList.add('dark');
                }
              })();
            `,
          }}
        />
      </head>
      <body className={`${roboto.variable} antialiased font-roboto`}>
         <ThemeProvider>
          <QueryClientContextProvider>
            {children}
          </QueryClientContextProvider>
         </ThemeProvider>
      </body>
    </html>
  );
};