import type { Metadata } from "next";
import localFont from "next/font/local";
import { Roboto } from 'next/font/google';
import "./globals.css";
import QueryClientContextProvider from "./query-client-provider";
import NavbarSidebarWrapper from "./NavbarSidebarWrapper";
import { ThemeProvider } from "./contexts/themeContext";
import '@fortawesome/fontawesome-svg-core/styles.css';
import { config } from '@fortawesome/fontawesome-svg-core';

config.autoAddCss = false;

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "YouTube",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body
        className={`${roboto.variable} antialiased font-roboto`}
      >
        <ThemeProvider>
          <QueryClientContextProvider>
            <NavbarSidebarWrapper />
            {children}
          </QueryClientContextProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}